SocialNetworkClient/SocialNetworkClient/Controllers/SettingsController.cs
using Newtonsoft.Json.Linq;
using SocialNetworkClient.Configs;
using SocialNetworkClient.Containers;
using SocialNetworkClient.Contracts;
using SocialNetworkClient.Enums;
using SocialNetworkClient.Models;
using SocialNetworkClient.Models.RequestsAndResponses;
using SocialNetworkClient.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SocialNetworkClient.Controllers
{
    public class SettingsController : Controller
    {
        public MainModel mainModel { get; set; }
        public IHttpClient httpClient { get; set; }
        public InputsValidator inputsValidator { get; set; }
        public SettingsController()
        {
            mainModel = new MainModel();

            httpClient = ClientContainer.container.GetInstance<IHttpClient>();
            inputsValidator = ClientContainer.container.GetInstance<InputsValidator>();
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EditSettings()
        {
            //returns the user's settings view
            return View("UserSettings", mainModel);
        }
        [HttpGet]
        public ActionResult ShowChangePassword(MainModel model)
        {
            //edits the user's password
            if (!IsTokenValid())
            {
                return Logout();
            }
            else
            {
                return View("ChangePassword", mainModel);
            }
        }
        [HttpGet]
        public ActionResult ShowEditDetails()
        {
            //edits the details of the user (except username and password)
            if (!IsTokenValid())
            {
                return Logout();
            }
            else
            {
                mainModel.LoggedInUser = GetMyUser();
                return View("EditDetails", mainModel);
            }
        }
        [HttpPost]
        public ActionResult EditDetails(MainModel model)
        {
            //edits the details of the user (except username and password)
            if (!IsTokenValid())
            {
                return Logout();
            }
            else
            {
                if (FeildsAreValid(model))
                {
                    model.LoggedInUser.Username = GetMyUser().Username;
                    Tuple<object, HttpStatusCode> returnTuple = httpClient.PostRequest(ApiConfigs.EditUserDetailsRoute, model.LoggedInUser);
                    if (returnTuple.Item2 == HttpStatusCode.OK)
                    {
                        JObject jobj = new JObject();
                        jobj = (JObject)returnTuple.Item1;
                        model.LoggedInUser = jobj.ToObject<User>();

                        ViewBag.SuccessMessage = "Details Updated Succesfuly";
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "An Error has occurred";
                    }
                    return View("UserSettings", model);
                }
                return View("EditDetails", model);
            }
        }
        [HttpPost]
        public ActionResult ChangePassword(MainModel model)
        {
            //edits the details of the user (except username and password)
            if (!IsTokenValid())
            {
                return Logout();
            }
            else
            {
                model.LoggedInUser = GetMyUser();
                if (PasswordsAreValid(model))
                {
                    model.EditPassword.Username = model.LoggedInUser.Username;
                    Tuple<object, HttpStatusCode> returnTuple = httpClient.PostRequest(ApiConfigs.EditUserPasswordRoute, model.EditPassword);
                    if (returnTuple.Item2 == HttpStatusCode.OK)
                    {
                        ViewBag.SuccessMessage = "Password Changed Succesfuly";
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "An Error has occurred";
                    }
                    return View("UserSettings", model);
                }
                return View("ChangePassword", model);
            }
        }

        private bool PasswordsAreValid(MainModel model)
        {
            //validates the passwords fields
            List<string> info = new List<string>();
            info.Add(inputsValidator.ValidateStrInput("Last Password", model.EditPassword.LastPassword, InputsConfigs.MinGenLen, InputsConfigs.MaxGenLen));
            info.Add(inputsValidator.ValidateStrInput("New Password", model.EditPassword.NewPassword, InputsConfigs.MinGenLen, InputsConfigs.MaxGenLen));
            info.Add(inputsValidator.ValidateStrInput("Password Confirm", model.EditPassword.NewPasswordConfirm, InputsConfigs.MinGenLen, InputsConfigs.MaxGenLen));
            if (model.EditPassword.NewPassword != model.EditPassword.NewPasswordConfirm)
            {
                info.Add("New password and confirm password dont match");
            }
            List<string> errors = info.Where(i => !string.IsNullOrWhiteSpace(i)).ToList();
            if (errors.Count == 0)
            {
                if (model.LoggedInUser.Password == model.EditPassword.LastPassword)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            else
            {
                for (int i = 0; i < errors.Count; i++)
                {
                    ViewData[$"Error{i}"] = errors[i];
                }
                return false;
            }

        }

        private bool FeildsAreValid(MainModel model)
        {
            //validates the fields and add the errors messages in to the View bag
            List<string> info = new List<string>();
            info.Add(inputsValidator.ValidateStrInput("Firstname", model.LoggedInUser.FirstName, InputsConfigs.MinGenLen, InputsConfigs.MaxGenLen));
            info.Add(inputsValidator.ValidateStrInput("Lastname", model.LoggedInUser.LastName, InputsConfigs.MinGenLen, InputsConfigs.MaxGenLen));
            info.Add(inputsValidator.ValidateRegEx("Email", InputsConfigs.EmailRegEx, model.LoggedInUser.Email));
            info.Add(inputsValidator.ValidateDateInput("Birthdate", model.LoggedInUser.BirthDate));
            info.Add(inputsValidator.ValidateStrInput("Address", model.LoggedInUser.Address, InputsConfigs.MinGenLen, InputsConfigs.MaxGenLen));
            info.Add(inputsValidator.ValidateStrInput("Work Location", model.LoggedInUser.WorkLocation, InputsConfigs.MinGenLen, InputsConfigs.MaxGenLen));
            List<string> errors = info.Where(i => !string.IsNullOrWhiteSpace(i)).ToList();
            if (errors.Count == 0)
            {
                return true;
            }
            else
            {
                for (int i = 0; i < errors.Count; i++)
                {
                    ViewData[$"Error{i}"] = errors[i];
                }
                return false;
            }
        }
      
        private ActionResult Logout()
        {
            //returns the user to the main window, with a pop message of logged out and clear the session data
            Session[MainConfigs.SessionFirstnameKey] = null;
            Session[MainConfigs.SessionLastnameKey] = null;
            Session[MainConfigs.SessionToken] = null;
            ViewBag.ErrorMessag = "Session Timeout, Logged out of the system";
            return View("~/Views/Home/Index.cshtml");
        }
        public bool IsTokenValid()
        {
            //validates the token from the session
            Tuple<object, HttpStatusCode> returnTuple = httpClient.PostRequest(ApiConfigs.ValidateTokenRoute, Session[MainConfigs.SessionToken]);
            if (returnTuple.Item2 == HttpStatusCode.OK)
            {
                return Convert.ToBoolean(returnTuple.Item1);
            }
            else
            {
                return false;
            }
        }
        private User GetMyUser()
        {
            //returns the user from this token
            Tuple<object, HttpStatusCode> returnTuple = httpClient.PostRequest(ApiConfigs.GetMyUserRoute, Session[MainConfigs.SessionToken]);
            if (returnTuple.Item2 == HttpStatusCode.OK)
            {
                JObject jobj = new JObject();
                jobj = (JObject)returnTuple.Item1;
                return jobj.ToObject<User>();
            }
            else
            {
                return null;
            }

        }
        private void SaveDetailsToSession(User user)
        {
            //saves the user's first and last name to the session for visualisation
            Session[MainConfigs.SessionFirstnameKey] = user.FirstName;
            Session[MainConfigs.SessionLastnameKey] = user.LastName;
        }
        private ActionResult UnvalidTokenRoute()
        {
            //returns the user to the main window, with a pop message of logged out and clear the session data
            Session[MainConfigs.SessionFirstnameKey] = null;
            Session[MainConfigs.SessionLastnameKey] = null;
            Session[MainConfigs.SessionToken] = null;
            ViewBag.ErrorMessag = "Session Timeout, Logged out of the system";
            return View("~/Views/Home/Index.cshtml");
        }
    }
}

SocialNetworkClient/SocialNetworkClient/Views/Settings/BlockedUsers.cshtml
@model SocialNetworkClient.Models.MainModel

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Blocked Users</h2>
@if (Model.UsersRep.Count > 0)
{
    foreach (var item in Model.UsersRep)
    {
        @Html.ActionLink($"{item.FullName}", "USERVIEW", item.Id) @Html.ActionLink("UnBlock", "UnfollowUser", item.Id) <br /><br />
    }
}
else
{
    <h3>You dont have any blocked users in your profile</h3>
}

@if (ViewBag.PageMessage != null)
{
    <script type="text/javascript">
                alert("@ViewBag.PageMessage");
    </script>
}

SocialNetworkClient/SocialNetworkClient/Views/Settings/ChangePassword.cshtml
@model SocialNetworkClient.Models.MainModel

@{
    ViewBag.Title = "EditPassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Password</h2>

@using (Html.BeginForm("ChangePassword", "Settings", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.EditPassword.LastPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.EditPassword.LastPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EditPassword.LastPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EditPassword.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.EditPassword.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EditPassword.NewPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EditPassword.NewPasswordConfirm, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.EditPassword.NewPasswordConfirm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EditPassword.NewPasswordConfirm, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}
@for (int i = 0; i < 6; i++)
{
    if (ViewData[$"Error{i}"] != null)
    {
        <script type="text/javascript">
                alert("@ViewData[$"Error{i}"]");
        </script>
    }
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SocialNetworkClient/SocialNetworkClient/Views/Settings/EditDetails.cshtml
@model SocialNetworkClient.Models.MainModel

@{
    ViewBag.Title = "EditDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditDetails</h2>


@using (Html.BeginForm("EditDetails", "Settings", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.LoggedInUser.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoggedInUser.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoggedInUser.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoggedInUser.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoggedInUser.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoggedInUser.LastName, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.LoggedInUser.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoggedInUser.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoggedInUser.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserRegister.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserRegister.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserRegister.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoggedInUser.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoggedInUser.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoggedInUser.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoggedInUser.WorkLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoggedInUser.WorkLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoggedInUser.WorkLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@for (int i = 0; i < 6; i++)
{
    if (ViewData[$"Error{i}"] != null)
    {
        <script type="text/javascript">
                alert("@ViewData[$"Error{i}"]");
        </script>
    }
}

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SocialNetworkClient/SocialNetworkClient/Views/Settings/UserSettings.cshtml
@model SocialNetworkClient.Models.MainModel

@{
    ViewBag.Title = "UserSettings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Settings</h2>
<br />

<button class="btn btn-info">
    @Html.ActionLink("Edit Profile Details", "ShowEditDetails")
</button>
<br /><br />
<button class="btn btn-info">
    @Html.ActionLink("Change Password", "ShowChangePassword")
</button>
<br /><br />
<button class="btn btn-info">
    @Html.ActionLink("Blocked Users", "BlockedUsers", "Home")
</button>
<br /><br />
<button class="btn btn-info">
    @Html.ActionLink(linkText: "Users I'm Following", actionName: "UsersImFollowing", controllerName: "Home")
</button>
<br /><br />
<button class="btn btn-info">
    @Html.ActionLink(linkText: "Users That Are Following Me", actionName: "UsersThatFollowMe", controllerName: "Home")
</button>
<br /><br />

@if (ViewBag.ErrorMessage != null)
{
    <script type="text/javascript">
    alert("@ViewBag.ErrorMessage");
    </script>
}
@if (ViewBag.SuccessMessage != null)
{
    <script type="text/javascript">
    alert("@ViewBag.SuccessMessage");
    </script>
}